version: '3.8'
services:
  authorizationuser:
    build:
      context: .
      dockerfile: ./AR_AuthorizationUser/Dockerfile
    ports:
      - "5000:80"

  commerce:
    build:
      context: .
      dockerfile: ./AR_Commerce/AR_Commerce/Dockerfile
    ports:
      - "5001:80"
